name: Robo
options:
  bundleIdPrefix: com.silv
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "26.0"

settings:
  base:
    DEVELOPMENT_TEAM: R3Z5CY34Q5
    CODE_SIGN_STYLE: Automatic
    PRODUCT_NAME: Robo
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 10
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    TARGETED_DEVICE_FAMILY: 1  # iPhone only

targets:
  Robo:
    type: application
    platform: iOS
    dependencies:
      - target: RoboShare
    sources:
      - path: Robo
        excludes:
          - "**/.DS_Store"
    entitlements:
      path: Robo/Robo.entitlements
      properties:
        com.apple.developer.healthkit: true
        com.apple.developer.healthkit.access: []
        com.apple.developer.networking.wifi-info: true
        aps-environment: development
        com.apple.security.application-groups:
          - group.com.silv.Robo
        keychain-access-groups:
          - $(AppIdentifierPrefix)group.com.silv.Robo
    settings:
      base:
        INFOPLIST_FILE: Robo/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.silv.Robo
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Robo/Robo.entitlements
    info:
      path: Robo/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - robo
            CFBundleURLName: com.silv.Robo
        ITSAppUsesNonExemptEncryption: false
        NSCameraUsageDescription: "Robo needs camera access to scan barcodes, capture photos, and perform LiDAR room scanning for AI analysis"
        NSPhotoLibraryUsageDescription: "Robo needs photo library access to save captured images"
        NSMotionUsageDescription: "Robo needs motion access to capture step count, distance, and activity data for AI analysis"
        NSBluetoothAlwaysUsageDescription: "Robo uses Bluetooth to detect nearby iBeacon devices for room-aware automations."
        NSHealthShareUsageDescription: "Robo reads your sleep, workout, and activity data to share with your AI agents."
        NSHealthUpdateUsageDescription: "Robo does not write health data, but HealthKit requires this description."
        NSSpeechRecognitionUsageDescription: "Robo uses speech recognition to let you create tasks and polls using your voice."
        NSMicrophoneUsageDescription: "Robo needs microphone access for voice input in chat."
        NSLocationWhenInUseUsageDescription: "Robo uses your location to tag sensor captures with where they were taken."
        NSLocationAlwaysAndWhenInUseUsageDescription: "Robo uses your location to tag sensor captures with where they were taken."
        UIBackgroundModes:
          - location
          - bluetooth-central
          - remote-notification

  RoboShare:
    type: app-extension
    platform: iOS
    sources:
      - path: RoboShare
        excludes:
          - "**/.DS_Store"
    entitlements:
      path: RoboShare/RoboShare.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.silv.Robo
        keychain-access-groups:
          - $(AppIdentifierPrefix)group.com.silv.Robo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.silv.Robo.ShareExtension
        PRODUCT_MODULE_NAME: RoboShare
        CODE_SIGN_ENTITLEMENTS: RoboShare/RoboShare.entitlements
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: RoboShare/Info.plist
    info:
      path: RoboShare/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleDisplayName: Robo
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: XPC!
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        ITSAppUsesNonExemptEncryption: false
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).ShareViewController
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsImageWithMaxCount: 1
    dependencies: []

  RoboTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RoboTests
        excludes:
          - "**/.DS_Store"
          - "Fixtures/**"
    resources:
      - path: RoboTests/Fixtures
        optional: true
    dependencies:
      - target: Robo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.silv.Robo.tests
        PRODUCT_MODULE_NAME: RoboTests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Robo.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Robo"
        BUNDLE_LOADER: "$(TEST_HOST)"
