name: Robo
options:
  bundleIdPrefix: com.silv
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "16.0"

settings:
  base:
    DEVELOPMENT_TEAM: R3Z5CY34Q5
    CODE_SIGN_STYLE: Automatic
    PRODUCT_NAME: Robo
    MARKETING_VERSION: 1.0
    CURRENT_PROJECT_VERSION: 7
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    TARGETED_DEVICE_FAMILY: 1  # iPhone only

targets:
  Robo:
    type: application
    platform: iOS
    sources:
      - path: Robo
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        INFOPLIST_FILE: Robo/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.silv.Robo
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Robo/Robo.entitlements
    info:
      path: Robo/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIApplicationSupportsIndirectInputEvents: true
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ITSAppUsesNonExemptEncryption: false
        NSCameraUsageDescription: "Robo needs camera access to scan barcodes, capture photos, and perform LiDAR room scanning for AI analysis"
        NSPhotoLibraryUsageDescription: "Robo needs photo library access to save captured images"
        NSMotionUsageDescription: "Robo needs motion access to capture step count, distance, and activity data for AI analysis"

  RoboTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RoboTests
        excludes:
          - "**/.DS_Store"
          - "Fixtures/**"
    resources:
      - path: RoboTests/Fixtures
        optional: true
    dependencies:
      - target: Robo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.silv.Robo.tests
        PRODUCT_MODULE_NAME: RoboTests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Robo.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Robo"
        BUNDLE_LOADER: "$(TEST_HOST)"
