// AUTO-GENERATED by registry/generate.js — DO NOT EDIT

/** Skill IDs from registry/features.json */
export const SKILL_IDS = {
  LIDAR: 'lidar',
  BARCODE: 'barcode',
  CAMERA: 'camera',
  PRODUCT_SCAN: 'product_scan',
  BEACON: 'beacon',
  HIT_LINKS: 'hit_links',
  MCP_BRIDGE: 'mcp_bridge',
  SCREENSHOT_SHARE: 'screenshot_share',
  MOTION: 'motion',
  HEALTH: 'health',
} as const;

/** Agent IDs from registry/features.json */
export const AGENT_IDS = {
  CLAUDE_CODE: 'claude_code',
  INTERIOR_DESIGNER: 'interior_designer',
  PRACTICAL_CHEF: 'practical_chef',
} as const;

/** App copy from registry/copy.json */
export const COPY = {
  "app": {
    "name": "Robo",
    "tagline": "The Context Cultivator",
    "og_title": "Robo — Phone Sensors as APIs for AI Agents",
    "og_description": "Open-source iOS app that turns your phone's sensors into APIs any AI agent can use. LiDAR, camera, barcodes — no iOS development required."
  },
  "hero": {
    "headline": "Your phone's sensors,<br>any AI agent.",
    "subheadline": "Open-source iOS app that turns LiDAR, camera, and barcodes into APIs. No Swift required."
  },
  "sections": {
    "for_developers": "For Developers",
    "for_everyone": "For Everyone",
    "from_anyone": "From Anyone"
  },
  "tabs": {
    "capture": "Capture",
    "history": "My Data",
    "chat": "Chat",
    "settings": "Settings"
  },
  "footer": {
    "tagline": "Open source. Privacy-first. Built entirely with Claude Code."
  }
} as const;

/** Feature status values */
export type FeatureStatus = 'active' | 'coming_soon' | 'disabled';

/** Feature category values */
export type FeatureCategory = 'sensor' | 'workflow' | 'platform';

/** Skill type values */
export type SkillType = 'lidar' | 'barcode' | 'camera' | 'productScan' | 'beacon' | 'motion' | 'health';
